Resources:
  CodeBuild:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: musicial-CodeBuild
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        # Downloaded build source code via CodePipeline
        Type: CODEPIPELINE
        Name: musicial
      Environment:
        # Linux container w/ node
        ComputeType: BUILD_GENERAL1_SMALL
        Type: LINUX_CONTAINER
        Image: "aws/codebuild/standard:5.0"
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub |
          version: 0.2
          phases:
            install:
              runtime-versions:
                nodejs: 14.x
            pre_build:
              commands:
                - echo Change directory...
                - cd website
                - cd web-app-musicial 
                - echo List directory files...
                - ls
                - echo Installing source NPM dependencies...
                - npm install
                - yarn add @types/react-dom
            build:
              commands:
                - echo List active directory...
                - ls
                - echo Build started on `date`
                - yarn run build
                - echo Finished build on `date`
                - ls
            post_build:
              commands:
                # copy the contents of /build to S3
                - aws s3 cp --recursive --acl public-read ./build s3://musicial.net/
                # set the cache-control headers for index.html to prevent
                # browser caching
                - aws s3 cp --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./build/index.html s3://musicial.net/
          artifacts:
            files:
              - '**/*'

  # IAM role for CodeBuild to interact w/ S3, CloudWatch and CloudFront
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /service-role/
      Policies:
        - PolicyName: rootBuild
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:GetBucketVersioning"
                  - "s3:PutObject"
                Resource:
                  - !GetAtt PipelineBucket.Arn
                  - !Join ["", [!GetAtt PipelineBucket.Arn, "/*"]]
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:GetBucketVersioning"
                  - "s3:PutObject"
                  - "s3:PutObjectAcl"
                Resource:
                  - !GetAtt Website.Arn
                  - !Join ["", [!GetAtt Website.Arn, "/*"]]
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "cloudfront:CreateInvalidation"
                Resource:
                  - "*"
