processLogin:
  handler: bin/processLogin
  runtime: go1.x
  timeout: 600
  package:
    patterns:
      - "!./*"
      - "bin/processLogin"

  events:
    - http:
        method: post
        path: login/process
        async: true
        cors: true
        #   origin:
        #   headers:

  environment:
    SPOTIFY_CLIENT_ID: "{{resolve:secretsmanager:dev/musicial/spotifyCredentials:SecretString:SPOTIFY_CLIENT_ID}}"
    SPOTIFY_REDIRECT_URI: "{{resolve:secretsmanager:dev/musicial/spotifyCredentials:SecretString:SPOTIFY_REDIRECT_URI}}"
    SPOTIFY_CLIENT_SECRET: "{{resolve:secretsmanager:dev/musicial/spotifyCredentials:SecretString:SPOTIFY_CLIENT_SECRET}}"
    REDIS_CLIENT_ADDRESS: "{{resolve:secretsmanager:dev/musicial/dbCredentials:SecretString:REDIS_CLIENT_ADDRESS}}"
    NEO4J_CLIENT_ADDRESS: "{{resolve:secretsmanager:dev/musicial/dbCredentials:SecretString:NEO4J_CLIENT_ADDRESS}}"
    NEO4J_CLIENT_USER: "{{resolve:secretsmanager:dev/musicial/dbCredentials:SecretString:NEO4J_CLIENT_USER}}"
    NEO4J_CLIENT_PASSWORD: "{{resolve:secretsmanager:dev/musicial/dbCredentials:SecretString:NEO4J_CLIENT_PASSWORD}}"

  role: { "Fn::GetAtt": ["ProcessLoginLambdaRole", "Arn"] }

supportingResources:
  Resources:
    ProcessLoginLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - "lambda.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          - PolicyName: "ProcessLoginLambdaLogPolicy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - "logs:CreateLogGroup"
                    - "logs:CreateLogStream"
                    - "logs:PutLogEvents"
                  Resource:
                    - "*"
          - PolicyName: "ProcessLoginLambdaEc2Policy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - "ec2:CreateNetworkInterface"
                    - "ec2:DescribeNetworkInterfaces"
                    - "ec2:DeleteNetworkInterface"
                  Resource:
                    - "*"
